### ISSUE TITLE
Cannot filter on desired resources selected by square brackets

### ISSUE THREAD

**Issue by aerfio** [crossplane-contrib/function-cel-filter#21]
### What happened?

I tried to filter resources based on existence of another resource. It seems to be supported, as this scenario is documented in root README.md as `has(desired.resources.bucket)`. This filter works, but once you switch to the one using `[` and `]`, for example when the name has a `-` in it it fails with:

```
crossplane: error: cannot render composite resource: pipeline step "filter-composed-resources" returned a fatal result: cannot evaluate CEL expression "has(desired.resources['table'])" for filter 0: cannot parse expression: ERROR: <input>:1:22: invalid argument to has() macro
                    | has(desired.resources['table'])
                    | .....................^
```

### How can we reproduce it?

```diff
diff --git a/example/composition.yaml b/example/composition.yaml
index 660c65d..209ed7b 100644
--- a/example/composition.yaml
+++ b/example/composition.yaml
@@ -46,4 +46,4 @@ spec:
         filters:
           # Only create the bucket if the XR's spec.export field is set to "S3".
           - name: bucket
-            expression: observed.composite.resource.spec.export == "S3"
+            expression: has(desired.resources['table'])
```
Apply this patch and run the command from ./example/README.md. Then change it like that
```diff
- desired.resources['table']
+ desired.resources.table
```
And see it pass through

### What environment did it happen in?
Function version: 
Tested on both v0.1.1 and also current main ([58e86dc](https://github.com/crossplane-contrib/function-cel-filter/commit/58e86dc1d21e154b8a05e34e34ca23a4488e1bca)), exact command used to run Function:
```bash
go run . --insecure --debug
```
Exact package when using v0.1.1: `xpkg.upbound.io/crossplane-contrib/function-cel-filter:v0.1.1`

**Comment by aerfio** [comment]
Strange this is that has technically should work IIUC, see:
- https://github.com/google/cel-spec/blob/master/doc/langdef.md#field-selection
- https://buf.build/crossplane/crossplane/docs/main:apiextensions.fn.proto.v1beta1#apiextensions.fn.proto.v1beta1.State - desired is [map[string]*Resource](https://github.com/crossplane/function-sdk-go/blob/11b59ad46986d3736e928c95ad5dc712aa15c724/proto/v1beta1/run_function.pb.go#L731)

**Comment by negz** [comment]
Hrm, interesting. Maybe `[]` doesn't work inside `has` specifically for some reason?

I'll admit I'm not a CEL expert. This function doesn't do anything too special though - we pretty much just pass the message to the CEL libraries. So I can't imagine the function is doing anything that would break how CEL is supposed to work. 🤔

**Comment by aerfio** [comment]
Ok, I got it: https://github.com/kubernetes/kubernetes/issues/118230#issuecomment-1564603679

instead of using `has` you have to use `in`, so it will be something like `"something" in desired.resources`. I'll try to get some time to create a PR which makes it clearer tomorrow 👍🏻
